name: Run Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'Developement' 

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set environment variables for Chrome
      run: |
        echo "CHROME_HEADLESS=false" >> $GITHUB_ENV
    - name: Run Maven Tests and Generate Report
      run: mvn clean test
    - name: Upload Extent Report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: ExtentReports/*
        if-no-files-found: warn
        include-hidden-files: false
